version: "3"
services:
  web-server:
    image: nginx:1.13-alpine
    networks:
     - server
    volumes:
     - /usr/app/nginx:/usr/src/app
     - /usr/app/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
     - /usr/app/nginx/conf/conf.d:/etc/nginx/conf.d
     - /usr/app/static:/usr/share/nginx/html:ro
     - ./conf/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=liuwill.com
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

